FROM	python:3.11.4-slim-buster

ENV		PYTHONDONTWRITEBYTECODE=1
ENV		PYTHONUNBUFFERED=1
ENV		DEBCONF_NOWARNINGS=yes
ENV		PATH=/home/app/.local/bin:$PATH

RUN		apt-get update &&			\
		apt-get install -y netcat

RUN		addgroup --system app &&		\
		adduser --system --group app

WORKDIR	/home/app/

COPY	./ ./

RUN		chown -R app:app ./
USER	app

RUN		pip install --upgrade pip
RUN		pip install -r ./requirements.txt

RUN		chmod +x ./entrypoint.dev.sh

ENTRYPOINT	[ "./entrypoint.dev.sh" ]
